### PR TITLE
Update libheif to 1.10.1

### PR DESCRIPTION
**Pull request by real-alexei**

### CODE REVIEW

**Comment by delphist** [comment]
we should merge this as it fixes several critical issues

**Comment by sentika** [comment]
@alexcorvi any chance that you merge this PR?

**Comment by markets** [comment]
Yes please! @alexcorvi let us know if we can help to move this forward 🙏🏼 it solves several problems (like: memory leaks, distorted images).

**Comment by elimisteve** [comment]
@alexcorvi Please merge this! Thanks :slightly_smiling_face:

**Comment by kdrendel99** [comment]
We need a merge, my man!

**Comment by markets** [comment]
Maybe it's time to start considering that this repo isn't actively maintained anymore, so we should look at starting a community fork where we can add some new maintainers and publish it to `npm`?

**Comment by elimisteve** [comment]
Agreed. Shall the new repo be your GitHub fork, @markets?

**Comment by markets** [comment]
This fork is maintained by @aselivanov. 

We are using it in production for some time with much better results compared to the released package in npm:

```diff
-  "heic2any": "^0.0.3",
+  "heic2any": "https://github.com/aselivanov/heic2any.git"
```

**Comment by Tuily** [comment]
@alexcorvi any updates on this one?

**Comment by amilich** [comment]
what happened here?

**Pull request closed without merging**
